language: python
python:
  - '2.7'
before_install:
  - openssl aes-256-cbc -K $encrypted_10b3eb08dcc1_key -iv $encrypted_10b3eb08dcc1_iv
    -in client-secret.json.enc -out client-secret.json -d
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-172.0.1-linux-x86_64.tar.gz
  - tar -xzf google-cloud-sdk-172.0.1-linux-x86_64.tar.gz
  - ./google-cloud-sdk/install.sh --quiet
  - ./google-cloud-sdk/bin/gcloud components install app-engine-python --quiet
  - pip install -r requirements.txt
  - pip install -t lib -r requirements.txt
  - pip install coveralls
  - pip install pylint
script:
  - find . -name "*.py" -path "./*" -not \( -path "./lib/*" -o -path "./google-cloud-sdk/*" \) | xargs pylint --reports=yes --rcfile=.pylintrc && coverage run --source=src test_runner.py --test-path tests/ -v ./google-cloud-sdk
after_success:
  coveralls
deploy:
  provider: gae
  keyfile: client-secret.json
  project: bot-test-mk
  version: v1
  skip_cleanup: true
  no_promote: true
after_deploy:
  - git stash --all
