runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: src.main.app
  login: admin
  secure: always

- url: /slack/event
  script: src.main.app
  secure: always

libraries:
- name: ssl
  version: "2.7.11"